### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by arnaudmolo**
Fix path to the main script

### CODE REVIEW

**Comment by arnaudmolo** [comment]
Hello @francoislaberge 
The package main script was incorrect, it was impossible to use the package :)

**Comment by seflless** [comment]
Thanks! Messed that up when migrating.

**Comment by seflless** [comment]
I published the fixed module to npm. Again, thank you for catching that.

**Comment by seflless** [comment]
@onesime Please do try it if you can, to see if it works for you.

**Pull request merged**
